### ISSUE TITLE
SyntaxError when parsing an AlmondGenerated function 

### ISSUE THREAD

**Issue by carmilso** [Stanford-Mobisocial-IoT-Lab/thingengine-platform-server#2]
At this [point](https://github.com/Stanford-Mobisocial-IoT-Lab/thingengine-core/blob/75b652964881144e6a2d0b995060c533eb130b55/lib/apps/app_executor.js#L113) I have as "code" argument the following string:
```
AlmondGenerated() {
    now => @com.twitter(id="twitter-account-xxxxxxxxxxxxxxxxxxxx").sink(status="Hey, testing tweets") ;
}
```
Unfortunately, It enters into the catch function with the following error:
```
Failed to add app: SyntaxError: Expected ",", ";", comment or whitespace but "." found.
SyntaxError: Expected ",", ";", comment or whitespace but "." found.
    at peg$buildException (/home/carlos/Development/CLEO-thingengine-platform-server/node_modules/thingtalk/lib/grammar.js:558:14)
    at Object.peg$parse [as parse] (/home/carlos/Development/CLEO-thingengine-platform-server/node_modules/thingtalk/lib/grammar.js:5519:13)
    at new AppExecutor (/home/carlos/Development/CLEO-thingengine-platform-server/node_modules/thingengine-core/lib/apps/app_executor.js:114:36)
    at Q.try (/home/carlos/Development/CLEO-thingengine-platform-server/node_modules/thingengine-core/lib/apps/database.js:46:23)
    at Promise.apply (/home/carlos/Development/CLEO-thingengine-platform-server/node_modules/thingengine-core/node_modules/q/q.js:1185:26)
    at Promise.promise.promiseDispatch (/home/carlos/Development/CLEO-thingengine-platform-server/node_modules/thingengine-core/node_modules/q/q.js:808:41)
    at /home/carlos/Development/CLEO-thingengine-platform-server/node_modules/thingengine-core/node_modules/q/q.js:1411:14
    at runSingle (/home/carlos/Development/CLEO-thingengine-platform-server/node_modules/thingengine-core/node_modules/q/q.js:137:13)
    at flush (/home/carlos/Development/CLEO-thingengine-platform-server/node_modules/thingengine-core/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by gcampax** [comment]
It looks like platform-server fell behind in the version of ThingTalk.
It should work now
